src/trim/account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import include, path, re_path

from trim import urls as t_urls

from . import views

app_name = "account"

urlpatterns = t_urls.paths_named(
    views,
    profile=(
        "ProfileView",
        (
            "",
            "profile/",
        ),
    ),
    edit=(
        "ProfileUpdateView",
        "profile/edit/",
    ),
    edit_username=(
        "ProfileUsernameUpdateView",
        "profile/edit/username/",
    ),
    edit_password=(
        "ProfilePasswordUpdateView",
        "profile/edit/user-information/",
    ),
    edit_email=(
        "ProfileEmailUpdateView",
        "profile/edit/email/now/",
    ),
    edit_email_verified=(
        "VerifiedEmailUpdateView",
        "profile/edit/email/",
    ),
    # home=('ProfileView', '',),
    logout=(
        "ProfileLogout",
        "logout/",
    ),
    login=(
        "ProfileLogin",
        "login/",
    ),
    new=(
        "ProfileNewAccount",
        "welcome/",
    ),
    inactive=(
        "ProfileInactiveAccount",
        "inactive/",
    ),
    forgot_success=(
        "ProfileForgotPasswordSuccessView",
        "forgot/sent/",
    ),
    invite=(
        "EmailInviteCreateView",
        "invite/",
    ),
    invites=(
        "EmailInviteListView",
        "invites/",
    ),
)


urlpatterns += [
    path(
        "forgot/",
        views.PasswordResetView.as_view(),
        name="admin_password_reset",
    ),
    path(
        "profile/edit/email/verify/",
        views.VerifyEmailTokenView.as_view(),
        name="verify_email_token",
    ),
    path(
        "profile/edit/email/verify/<str:uuid>/",
        views.VerifyEmailTokenView.as_view(),
        name="verify_email_token",
    ),
]

src/trim/account/views/profile.py
from django.http import Http404

# from django.utils.translation import ugettext_lazy  as _
from django.utils.translation import gettext as _

from trim import views


class ProfileNewAccount(views.TemplateView):
    template_name = "account/new-profile.html"


class ProfileView(views.TemplateView):
    template_name = "account/profile.html"


class ProfileUpdateView(views.UpdateView):
    success_url = views.reverse_lazy("account:profile")
    template_name = "account/profile_form.html"
    model = views.get_user_model()
    fields = (
        "first_name",
        "last_name",
        # 'username',
    )

    def get_object(self, queryset=None):
        """
        Return the object the view is displaying.
        Require `self.queryset` and a `pk` or `slug` argument in the URLconf.
        Subclasses can override this to return any object.
        """
        # Use a custom queryset if provided; this is required for subclasses
        # like DateDetailView
        if queryset is None:
            queryset = self.get_queryset()
        # Next, try looking up by primary key.
        pk = self.kwargs.get(self.pk_url_kwarg)
        slug = self.kwargs.get(self.slug_url_kwarg)
        if pk is not None:
            queryset = queryset.filter(pk=pk)
        queryset = queryset.filter(pk=self.request.user.pk)

        try:
            # Get the single item from the filtered queryset
            obj = queryset.get()
        except queryset.model.DoesNotExist as err:
            d = {"verbose_name": queryset.model._meta.verbose_name}
            msg = _("No %(verbose_name)s found matching the query") % d
            raise Http404(msg) from err
        return obj


class ProfileUsernameUpdateView(ProfileUpdateView):
    fields = ("username",)


class ProfileEmailUpdateView(ProfileUpdateView):
    fields = ("email",)

src/trim/account/templates/account_backup/accountemail_form.html
{% extends "theme/form-page.html" %}

{% block header_title %}Your Email{% endblock header_title %}
{% block secondary_title %}Edit{% endblock secondary_title %}

{% block right_content %}
    <p>Change your email address to the preferred for contact and receipts. A confirmation email is sent to the both email addresses before the change occurs. <br>Please ensure to check the old and new accounts before accessing the site. </p>
{% endblock right_content %}

src/trim/account/templates/account_backup/base.html
{% extends "primary2/secondary-page.html" %}

{% load static wagtailcore_tags wagtailuserbar %}

{% block content_container %}

    {% block hero_header %}
        <div class="new-hero-header">
        {% block hero_content %}
            {% include "v4/secondary-header.html" with secondary="Login" primary='Account' %}
        {% endblock hero_content %}
        </div>
    {% endblock hero_header %}

    <div class="">
        <div class="margin-top-5vh flex-down">
        {% block deep_content %}{% endblock %}
        </div>
    </div>

{% endblock %}

src/trim/account/templates/account_backup/forgotpasswordrecord_form.html
{% extends "account/base.html" %}

{% block hero_content %}
    {% include "v4/secondary-header.html" with primary="Login" secondary="Forgot Password" %}
{% endblock hero_content %}

{% block deep_content %}
    {{ block.super }}
    <p>Please enter your email address. If it exists in our system, you'll recieve a link to reset your password.</p>
    <div class="flex-center">
        {% include "account/sub/login_form.html" %}
    </div>

{% endblock %}

src/trim/account/templates/account_backup/form.html
{% extends "account/base.html" %}


{% block title %}Form{% endblock %}
{% block body_class %}{{ block.super }} account/form{% endblock %}


{% block hero_content %}
    {% include "v4/secondary-header.html" with primary="Account" secondary="Form" %}
{% endblock hero_content %}


{% block content %}
    {{ block.super }}

    <div class="flex-center">
        <div class="flex-down gap-1">
            {% include 'generic-form.html' %}
        </div>
    </div>
{% endblock %}

src/trim/account/templates/account_backup/logged-out.html
{% extends "account/base.html" %}

{% block hero_content %}
    {% include "v4/secondary-header.html" with primary="Account" secondary="Logged Out" %}
{% endblock hero_content %}

{% block deep_content %}
    {{ block.super }}


    {% if user.is_anonymous %}
        <p>You are logged out of your account. <br>Thank you for your time today.</p>

        {% include "account/sub/login_prompt.html" %}

    {% else %}

        <h2>A Potential Issue Occured</h2>

        <p>You should have been logged out of your website profile, but we've detected you are still logged-in.
            <br>If this message is unexpected please attempt to <a href='{% url "logout" %}'>logout</a> again.
        </p>
    {% endif %}

{% endblock %}

src/trim/account/templates/account_backup/login-v1.html
{% extends "account/base.html" %}

{% block hero_content %}
    {% include "v4/secondary-header.html" with primary="Login" secondary="Your Account" %}
{% endblock hero_content %}

{% block deep_content %}
    <div class="flex-down">
        <div class="flex-center">
            {% include "account/sub/primary_login_form.html" %}
        </div>
    </div>
{% endblock %}

src/trim/account/templates/account_backup/login-v2.html
{% theme "form" %}
{# extends "account/base.html" #}


{% block header_title %}Login{% endblock header_title %}
{% block secondary_title %}Account{% endblock secondary_title %}
{% block title %}Login{% endblock title %}
{% block body_class %}login-form {{ block.super }}{% endblock body_class %}

{% block info_area %}
    <h2>Your Account</h2>
    <p>Log into your Princeton Scientific account, or use your social login below</p>
    <div class="actions btns flex-across">
        {% include "account/sub/social_buttons.html" %}
    </div>
{% endblock info_area %}


{% block below_form_area %}
    <div>
        <a href='{% url "account:admin_password_reset" %}'>Forgot Password</a>
    </div>

    <div class="actions btns flex-across">
        {% include "account/sub/register_button.html" %}

    </div>

{% endblock below_form_area %}

src/trim/account/templates/account_backup/login.html
{% extends "./login-v1.html" %}

src/trim/account/templates/account_backup/new-profile.html
{% extends "account/base.html" %}
{% load static wagtailcore_tags wagtailuserbar %}
{% block hero_content %}
{% include "v4/secondary-header.html" with primary="Profile" secondary="New Account" %}
{% endblock hero_content %}

{% block deep_content %}
    <h1>Welcome {{ user.first_name }}</h1>

    <p>Your new account has been created.</p>
    <a href='{% url "account:logout" %}'>Logout</a>
    <a href='{% url "account:profile" %}'>Account</a>

    <div class="template_name">page < new-profile</div>
{% endblock %}


src/trim/account/templates/account_backup/original_profile.html
{% extends "base.html" %}
{% load static wagtailcore_tags wagtailuserbar %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/mock1.css' %}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Rubik:wght@439&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Hind+Siliguri:wght@300;400;500;600;700&family=Hind+Vadodara:wght@300;400;500;600;700&display=swap" rel="stylesheet">
{% endblock %}

{% block content %}

{% if user.is_anonymous %}
    {% include "account/login_prompt.html" %}
{% else %}

    <h2>profile {{ user }}</h2>

    <ul>
        <li>name, email address</li>
        <li>connected logins</li>
        <li>addresses</li>
        <li>organisations</li>
        <li>puchases</li>
        <li>wishlists</li>
    </ul>
{% endif %}

    <p>This is your account area, find all your personal assets here.</p>
{% endblock %}

src/trim/account/templates/account_backup/password-reset-done.html


{% extends "account/base.html" %}

{% block hero_content %}
    {% include "v4/secondary-header.html" with primary="Login" secondary="Reset Sent" %}
{% endblock hero_content %}

{% block content %}
    {{ block.super }}

<div class="max-width-1200px">

<h3>Password reset complete</h3>
<p>You may now use your new password to login.</p>
</div>

{% endblock %}

src/trim/account/templates/account_backup/password_update_form.html
{% theme "form" with header_title="Your Password" secondary_title="Change" %}
{# extends "theme/form-page.html" #}


{% block header_title %}Your Password{% endblock header_title %}
{% block secondary_title %}Change{% endblock secondary_title %}

src/trim/account/templates/account_backup/profile.html
{% extends "account/base.html" %}
{% load link %}

{# include "v1/secondary-header.html" with primary="Profile" secondary="Your Account" #}

{% block hero_content %}
    {% include "v4/secondary-header.html" with secondary="Your Profile" primary='Account' %}

    <div class="v1 v1p5 hero-header secondary flex-grow hidden">

        <div class="content flex-reverse flex-down">
            <h1 class="margin-left-10vw">Profile</h1>
            <hr class="grow">
            <h2 class="margin-left-10vw">Your Account</h2>
        </div>

        <div class="actions btns margin-left-auto margin-right-10vw">

        {% if user.is_anonymous %}
            {% link "admin:login" "Login" %}
        {% else %}
            {% link "account:logout" "Logout" %}
        {% endif %}

            {% if user.is_staff %}
                {% link "admin:index" "Admin" %}
                {% link "wagtailadmin_home" "CMS" %}
            {% endif %}
        </div>
    </div>
{% endblock hero_content %}


{% block deep_content %}

    {% if user.is_anonymous %}
        {% include "account/sub/login_prompt.html" %}
    {% else %}

        <div class="flex-down gap-2">

            <div class="font-size-1p2em">
                <ul class="strong-table table user-links">
                    <li>
                        <span>
                        {% link "account:edit" "Name" %}
                        {% link "account:edit_email_verified" "email address" %}
                        </span>
                        <span>
                            <p>All About you</p>
                            <div class="flex-across gap-1">
                                <div class="flex-across gap-p5em">
                                {% link "account:edit" user.first_name %}
                                {% link "account:edit" user.last_name %}
                                </div>
                                <div>
                                    {% link "account:edit_email_verified" user.email %}
                                </div>
                            </div>
                        </span>
                    </li>
                    <li>
                        <span>
                        {% link "account:edit_password" "Password" %}
                        {% link "account:edit_username" "Username" %}
                        </span>
                        <span>
                            <div>
                                <p>Your login details</p>
                                <div class="flex across gap-1">
                                    {% link "account:edit_username" user.username %}
                                    {% link "account:edit_password" "Change Password" %}
                                </div>

                            </div>
                        </span>
                    </li>
                    <li>
                        <span>
                            {% link "baskets:purchases" "purchases" %}
                        </span>
                        <span>
                            <div class="flex-down">
                                <p>Your purchases and receipts.</p>
                                {% link "baskets:purchases" "View" %}
                            </div>
                        </span>
                    </li>
                    <li>
                        <span>
                            {% link "baskets:shippingaccount_list" "Shipping Accounts" %}
                        </span>
                        <span>
                            <div>
                                <p>Your business shipping account details</p>
                                {% link "baskets:shippingaccount_list" "Shipping Accounts" %}
                            </div>
                        </span>
                    </li>
                    {% comment "no internal addresses for stripe" %}
                    <li>
                        {% link "locality:index" "addresses" %}
                    </li>
                    {% endcomment %}

                    <li>
                        <span>
                            {% link "orgs:index" "organisations" %}
                        </span>
                        <span>
                            <p>Onboard your company for continued support and reseller discounts</p>
                        </span>
                    </li>

                    {% if user.is_staff %}


                    <li>
                        <span>
                            {% link "baskets:user" "baskets" %}
                        </span>
                        <span>
                            <p>Your previous shopping carts</p>
                        </span>
                    </li>

                     <li>
                        <span>stocks</span>
                        <span>
                            <ul>
                                <li>{% link "stocks:counts" "list" %}</li>
                                <li>{% link "stocks:list" "uploaded" %}</li>
                                <li>{% link "stocks:upload" "upload new" %}</li>
                            </ul>
                            <ul>
                                <li>{% link "stocks:notification-all-list" "notifications" %}</li>
                                <li>{% link 'stocks:notification-list' 'users' "Quick List" %}</li>
                            </ul>
                        </span>
                    </li>
                    <li>
                        <span>pricing</span>
                        <span>
                            <ul>
                                <li>{% link "pricing:index" "list" %}</li>
                            </ul>
                        </span>
                    </li>
                    <li>
                        <span>baskets</span>
                        <span>
                            <ul>
                                <li>{% link "baskets:all" "all" %}</li>
                            </ul>
                        </span>
                    </li>
                    {% endif %}

                </ul>
            </div>


        {% if user.is_staff %}
            <h2>Admin Extras</h2>

            <div class="flex-down gap-2">
                <div class="admin-links">
                    <p>You can see these extra staff links, as you are designated a staff member within the admin.</p>
                </div>

                <div class="hyperlinks">
                    <p>Your Hyperlinks</p>
                    {% include "core/hyperlink_list.html" %}
                </div>

            </div>

        {% endif %}

        </div>

    {% endif %}

{% endblock %}

src/trim/account/templates/account_backup/profile_form.html
{% theme "form" with secondary_title="Your Profile" header_title='Edit' %}
{# extends "theme/form-page.html" #}